auth_source: "your-eero-email-or-phone"
session_file: "./data/eero_session.cookie"
network_name: "Sf"
poll_interval_seconds: 60
database: "./data/eero_intel.db"
dsarexport: "./data/personal_data.zip"
web:
  host: "0.0.0.0"
  port: 8080
notifications:
  webhook_urls: []   # Slack/Discord/Teams generic webhooks
  pushcut_url: ""
devices:
  - name: "MyQ-408"
    match: { names: ["MyQ-408"] }
    notify: true
  - name: "Tstat-0BFEBD"
    match: { names: ["Tstat-0BFEBD"] }
    notify: true
  - name: "wlan0"
    match: { names: ["wlan0"], macs: ["38:1f:8d:c8:ed:85"] }
    notify: true
  - name: "XBOX"
    match: { names: ["XBOX"] }
    notify: true
  - name: "localhost"
    match: { names: ["localhost"] }
    notify: true
  - name: "Samsung"
    match: { names: ["Samsung"], macs: ["cc:6e:a4:90:14:5b"] }
    notify: true
  - name: "Jere iPhone"
    match: { names: ["Jere iPhone"], macs: ["72:c0:e8:62:51:50"] }
    notify: true
  - name: "Cooper iPhone"
    match: { names: ["Cooper iPhone"], macs: ["a6:4c:c9:b6:9c:c0"] }
    notify: true
  - name: "Myles iPhone"
    match: { names: ["Myles iPhone"], macs: ["e6:fc:70:8b:79:a1"] }
    notify: true
  - name: "DESKTOP-UI1LV9VF"
    match: { names: ["DESKTOP-UI1LV9VF"] }
    notify: true
  - name: "PS4-5654B9"
    match: { names: ["PS4-5654B9"] }
    notify: true
  - name: "Raurieforreal"
    match: { names: ["Raurieforreal"] }
    notify: true
  - name: "Guest Device"
    match: { names: ["Unnamed Device"] }
    notify: true
